//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestExecWin.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GeneralCmdLineArgs {
            get {
                return ((string)(this["GeneralCmdLineArgs"]));
            }
            set {
                this["GeneralCmdLineArgs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"// App set 1 of 8. Enter each test app on a single line
// Empty lines and lines starting with ""//"" are ignored

C:\YourTargetDir\Debug\YourTestAppOne.exe -optionalArgs
C:\YourTargetDir\Debug\YourNextTestAppTwo.exe

// To automatically generate entries here check import
// possibilities via button ""Export/Import""")]
        public string TestApps1 {
            get {
                return ((string)(this["TestApps1"]));
            }
            set {
                this["TestApps1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"// App set 2 of 8. Enter each test app on a single line
// Empty lines and lines starting with ""//"" are ignored

C:\YourTargetDir\Debug\YourTestAppOne.exe -optionalArgs
C:\YourTargetDir\Debug\YourNextTestAppTwo.exe

// To automatically generate entries here check import
// possibilities via button ""Export/Import""

")]
        public string TestApps2 {
            get {
                return ((string)(this["TestApps2"]));
            }
            set {
                this["TestApps2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"// App set 3 of 8. Enter each test app on a single line
// Empty lines and lines starting with ""//"" are ignored

C:\YourTargetDir\Debug\YourTestAppOne.exe -optionalArgs
C:\YourTargetDir\Debug\YourNextTestAppTwo.exe

// To automatically generate entries here check import
// possibilities via button ""Export/Import""

")]
        public string TestApps3 {
            get {
                return ((string)(this["TestApps3"]));
            }
            set {
                this["TestApps3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1. Set of test apps (rename this)")]
        public string DescTestApps1 {
            get {
                return ((string)(this["DescTestApps1"]));
            }
            set {
                this["DescTestApps1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2. Set of test apps (rename this)")]
        public string DescTestApps2 {
            get {
                return ((string)(this["DescTestApps2"]));
            }
            set {
                this["DescTestApps2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3. Set of test apps (rename this)")]
        public string DescTestApps3 {
            get {
                return ((string)(this["DescTestApps3"]));
            }
            set {
                this["DescTestApps3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CheckForMemoryLeaks {
            get {
                return ((bool)(this["CheckForMemoryLeaks"]));
            }
            set {
                this["CheckForMemoryLeaks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int IdxGroupsAndFuncs {
            get {
                return ((int)(this["IdxGroupsAndFuncs"]));
            }
            set {
                this["IdxGroupsAndFuncs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int IdxSortOrder {
            get {
                return ((int)(this["IdxSortOrder"]));
            }
            set {
                this["IdxSortOrder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LogIsVisible {
            get {
                return ((bool)(this["LogIsVisible"]));
            }
            set {
                this["LogIsVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int IdxOutputLevel {
            get {
                return ((int)(this["IdxOutputLevel"]));
            }
            set {
                this["IdxOutputLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int IdxCurrentTestApps {
            get {
                return ((int)(this["IdxCurrentTestApps"]));
            }
            set {
                this["IdxCurrentTestApps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OptionsAreVisible {
            get {
                return ((bool)(this["OptionsAreVisible"]));
            }
            set {
                this["OptionsAreVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"// App set 4 of 8. Enter each test app on a single line
// Empty lines and lines starting with ""//"" are ignored

C:\YourTargetDir\Debug\YourTestAppOne.exe -optionalArgs
C:\YourTargetDir\Debug\YourNextTestAppTwo.exe

// To automatically generate entries here check import
// possibilities via button ""Export/Import""

")]
        public string TestApps4 {
            get {
                return ((string)(this["TestApps4"]));
            }
            set {
                this["TestApps4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"// App set 5 of 8. Enter each test app on a single line
// Empty lines and lines starting with ""//"" are ignored

C:\YourTargetDir\Debug\YourTestAppOne.exe -optionalArgs
C:\YourTargetDir\Debug\YourNextTestAppTwo.exe

// To automatically generate entries here check import
// possibilities via button ""Export/Import""
")]
        public string TestApps5 {
            get {
                return ((string)(this["TestApps5"]));
            }
            set {
                this["TestApps5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4. Set of test apps (rename this)")]
        public string DescTestApps4 {
            get {
                return ((string)(this["DescTestApps4"]));
            }
            set {
                this["DescTestApps4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5. Set of test apps (rename this)")]
        public string DescTestApps5 {
            get {
                return ((string)(this["DescTestApps5"]));
            }
            set {
                this["DescTestApps5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int IdxMaxWaitTime {
            get {
                return ((int)(this["IdxMaxWaitTime"]));
            }
            set {
                this["IdxMaxWaitTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"// App set 6 of 8. Enter each test app on a single line
// Empty lines and lines starting with ""//"" are ignored

C:\YourTargetDir\Debug\YourTestAppOne.exe -optionalArgs
C:\YourTargetDir\Debug\YourNextTestAppTwo.exe

// To automatically generate entries here check import
// possibilities via button ""Export/Import""

")]
        public string TestApps6 {
            get {
                return ((string)(this["TestApps6"]));
            }
            set {
                this["TestApps6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"// App set 7 of 8. Enter each test app on a single line
// Empty lines and lines starting with ""//"" are ignored

C:\YourTargetDir\Debug\YourTestAppOne.exe -optionalArgs
C:\YourTargetDir\Debug\YourNextTestAppTwo.exe

// To automatically generate entries here check import
// possibilities via button ""Export/Import""

")]
        public string TestApps7 {
            get {
                return ((string)(this["TestApps7"]));
            }
            set {
                this["TestApps7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"// App set 8 of 8. Enter each test app on a single line
// Empty lines and lines starting with ""//"" are ignored

C:\YourTargetDir\Debug\YourTestAppOne.exe -optionalArgs
C:\YourTargetDir\Debug\YourNextTestAppTwo.exe

// To automatically generate entries here check import
// possibilities via button ""Export/Import""

")]
        public string TestApps8 {
            get {
                return ((string)(this["TestApps8"]));
            }
            set {
                this["TestApps8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6. Set of test apps (rename this)")]
        public string DescTestApps6 {
            get {
                return ((string)(this["DescTestApps6"]));
            }
            set {
                this["DescTestApps6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7. Set of test apps (rename this)")]
        public string DescTestApps7 {
            get {
                return ((string)(this["DescTestApps7"]));
            }
            set {
                this["DescTestApps7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8. Set of test apps (rename this)")]
        public string DescTestApps8 {
            get {
                return ((string)(this["DescTestApps8"]));
            }
            set {
                this["DescTestApps8"] = value;
            }
        }
    }
}
